[PHP]
max_execution_time=300
max_input_time=60
memory_limit=512M
post_max_size=70M
upload_max_filesize=64M
max_file_uploads=20
max_input_vars=3000
opcache.memory_consumption=64
opcache.validate_timestamps=On
variables_order="EGPCS"
display_errors=On
log_errors=On
zend.assertions=1
short_open_tag = Off
;error_log = /var/log/php/error.log

[Date]
date.timezone = ${TIMEZONE}

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.revalidate_freq=0
opcache.validate_timestamps=1

[pcov]
pcov.enabled=1
pcov.directory=src